### PR TITLE
add Tik Tok logo

### PR DESCRIPTION
**Pull request by radumro**
Please let me know if this is helpful

### CODE REVIEW

**Comment by fatawesome** [comment]
Hi @radumro. Line Awesome is not just a collection of icons, but a font :) What I can do is tell our designers (who draw icons for https://icons8.com/icons) to create a TikTok icon.

**Comment by fatawesome** [comment]
Also, check this out: https://icons8.com/icons/set/tiktok-logo

**Comment by radumro** [comment]
> Hi @radumro. Line Awesome is not just a collection of icons, but a font :) What I can do is tell our designers (who draw icons for https://icons8.com/icons) to create a TikTok icon.

i was hoping that if you have the svg it will be easier to import it in the font and not design it from scratch. i don't know what is your process. sorry for disturbing ...

**Comment by jhnbkr** [comment]
@fatawesome has there been update regarding implementing TikTok? With the continued surge in popularity we are now including TikTok social links by default, and having access to the icon through Line Awesome would be advantageous.

**Pull request closed without merging**
